version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: handydz-postgres
    environment:
      POSTGRES_DB: handydzdb
      POSTGRES_USER: handydz
      POSTGRES_PASSWORD: handydz
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U handydz -d handydb"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:
