services:
  - type: web
    name: handydz
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: "" # Not needed for Docker
    startCommand: "" # Not needed for Docker
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: handydz-db
          property: connectionString

databases:
  - name: handydz-db
    plan: free
